import { Framework } from "@/components/FrameworkSelector";

// Mock AI responses for different frameworks
// In Phase 2, this will be replaced with actual Google Generative AI (Gemini) calls

const mockResponses: Record<Framework, Record<string, string>> = {
  html: {
    default: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UI Component</title>
  <style>
    .card {
      max-width: 400px;
      margin: 2rem auto;
      padding: 2rem;
      background: #ffffff;
      border-radius: 12px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    }
    
    .card-title {
      font-size: 1.5rem;
      font-weight: 600;
      color: #1f2937;
      margin-bottom: 0.5rem;
    }
    
    .card-description {
      color: #6b7280;
      line-height: 1.6;
      margin-bottom: 1.5rem;
    }
    
    .btn {
      display: inline-block;
      padding: 0.75rem 1.5rem;
      background: #3b82f6;
      color: white;
      border: none;
      border-radius: 8px;
      font-weight: 500;
      cursor: pointer;
      transition: background 0.2s;
    }
    
    .btn:hover {
      background: #2563eb;
    }
  </style>
</head>
<body>
  <div class="card">
    <h2 class="card-title">Welcome to PixelPro</h2>
    <p class="card-description">
      This is a sample component generated by AI. 
      Customize it to match your design needs.
    </p>
    <button class="btn">Get Started</button>
  </div>
</body>
</html>`,
  },
  tailwind: {
    default: `<!-- Component: Modern Card with Tailwind CSS -->
<div class="max-w-md mx-auto mt-8">
  <div class="bg-white rounded-2xl shadow-lg overflow-hidden">
    <!-- Card Header with Gradient -->
    <div class="bg-gradient-to-r from-blue-500 to-purple-600 px-6 py-8">
      <h2 class="text-2xl font-bold text-white">
        Welcome to PixelPro
      </h2>
      <p class="text-blue-100 mt-2">
        AI-powered component generation
      </p>
    </div>
    
    <!-- Card Body -->
    <div class="p-6">
      <p class="text-gray-600 leading-relaxed">
        This component was generated using AI. It features 
        a modern design with Tailwind CSS utility classes 
        for easy customization.
      </p>
      
      <!-- Feature List -->
      <ul class="mt-4 space-y-2">
        <li class="flex items-center gap-2 text-gray-700">
          <svg class="w-5 h-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
          </svg>
          Fully responsive design
        </li>
        <li class="flex items-center gap-2 text-gray-700">
          <svg class="w-5 h-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
          </svg>
          Easy to customize
        </li>
        <li class="flex items-center gap-2 text-gray-700">
          <svg class="w-5 h-5 text-green-500" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
          </svg>
          Production ready
        </li>
      </ul>
    </div>
    
    <!-- Card Footer -->
    <div class="px-6 py-4 bg-gray-50 border-t border-gray-100">
      <button class="w-full bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-4 rounded-lg transition-colors">
        Get Started
      </button>
    </div>
  </div>
</div>`,
  },
  react: {
    default: `import React, { useState } from 'react';

// Modern Card Component with React + Tailwind CSS
// Generated by PixelPro AI

interface CardProps {
  title?: string;
  description?: string;
  onAction?: () => void;
}

const Card: React.FC<CardProps> = ({
  title = "Welcome to PixelPro",
  description = "AI-powered component generation made simple.",
  onAction
}) => {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <div 
      className="max-w-md mx-auto"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <div className={\`
        bg-white rounded-2xl shadow-lg overflow-hidden
        transition-all duration-300
        \${isHovered ? 'shadow-xl -translate-y-1' : ''}
      \`}>
        {/* Gradient Header */}
        <div className="bg-gradient-to-r from-cyan-500 to-blue-600 px-6 py-8">
          <h2 className="text-2xl font-bold text-white">
            {title}
          </h2>
          <p className="text-cyan-100 mt-2">
            {description}
          </p>
        </div>

        {/* Content */}
        <div className="p-6">
          <div className="space-y-4">
            <Feature text="Fully responsive design" />
            <Feature text="TypeScript support" />
            <Feature text="Easy to customize" />
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-gray-50 border-t">
          <button
            onClick={onAction}
            className="w-full bg-gradient-to-r from-cyan-500 to-blue-600 
                       hover:from-cyan-600 hover:to-blue-700
                       text-white font-medium py-3 px-4 rounded-lg 
                       transition-all duration-200 transform hover:scale-[1.02]"
          >
            Get Started
          </button>
        </div>
      </div>
    </div>
  );
};

// Helper component for feature items
const Feature: React.FC<{ text: string }> = ({ text }) => (
  <div className="flex items-center gap-3">
    <div className="w-5 h-5 rounded-full bg-green-100 flex items-center justify-center">
      <svg 
        className="w-3 h-3 text-green-600" 
        fill="currentColor" 
        viewBox="0 0 20 20"
      >
        <path 
          fillRule="evenodd" 
          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" 
          clipRule="evenodd"
        />
      </svg>
    </div>
    <span className="text-gray-700">{text}</span>
  </div>
);

export default Card;`,
  },
};

/**
 * Generates component code by calling the backend API
 * Currently the backend returns mock responses, but the API structure
 * is ready for real AI integration in Phase 2
 * 
 * @param prompt - User's component description
 * @param framework - Selected framework (html, tailwind, react)
 * @returns Generated component code
 */
export const generateCode = async (
  prompt: string,
  framework: Framework
): Promise<string> => {
  try {
    // Call the backend API
    const response = await fetch(`${API_CONFIG.baseUrl}${API_CONFIG.endpoints.generate}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        prompt,
        framework,
      }),
    });

    // Check if request was successful
    if (!response.ok) {
      const error = await response.json();
      throw new Error(error.error || "Failed to generate code");
    }

    // Parse and return the generated code
    const data = await response.json();
    return data.code;
  } catch (error) {
    console.error("API Error:", error);
    
    // Fallback to local mock if backend is not available
    // This allows the frontend to work independently during development
    console.warn("Backend unavailable, using local mock response");
    await new Promise((resolve) => setTimeout(resolve, 1000));
    return mockResponses[framework].default;
  }
};

/**
 * API service configuration
 * Points to the backend server
 */
export const API_CONFIG = {
  baseUrl: import.meta.env.VITE_API_URL || "http://localhost:3001/api",
  endpoints: {
    generate: "/generate",
    health: "/health",
  },
};
