import dotenv from "dotenv";
dotenv.config();

import { GoogleGenerativeAI } from "@google/generative-ai";
const generationCache = new Map();

// ============================================
// MOCK AI RESPONSES
// ============================================

const mockResponses = {
  html: {
    default: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>UI Component</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #f9fafb;
      padding: 2rem;
    }
    
    .card {
      max-width: 400px;
      margin: 0 auto;
      background: white;
      border-radius: 16px;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
      overflow: hidden;
    }
    
    .card-header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      padding: 2rem;
      color: white;
    }
    
    .card-title {
      font-size: 1.75rem;
      font-weight: 700;
      margin-bottom: 0.5rem;
    }
    
    .card-subtitle {
      opacity: 0.9;
      font-size: 0.95rem;
    }
    
    .card-body {
      padding: 1.5rem;
    }
    
    .card-text {
      color: #6b7280;
      line-height: 1.6;
      margin-bottom: 1.5rem;
    }
    
    .btn {
      display: block;
      width: 100%;
      padding: 0.875rem;
      background: #667eea;
      color: white;
      border: none;
      border-radius: 10px;
      font-size: 1rem;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.2s;
    }
    
    .btn:hover {
      background: #5568d3;
      transform: translateY(-1px);
      box-shadow: 0 4px 12px rgba(102, 126, 234, 0.4);
    }
  </style>
</head>
<body>
  <div class="card">
    <div class="card-header">
      <h2 class="card-title">PixelPro Component</h2>
      <p class="card-subtitle">Generated by AI</p>
    </div>
    <div class="card-body">
      <p class="card-text">
        This is a beautiful, responsive component created with pure HTML and CSS. 
        Customize the styles and content to match your needs.
      </p>
      <button class="btn">Get Started</button>
    </div>
  </div>
</body>
</html>`,
    
    button: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Button Component</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background: #f9fafb;
    }
    
    .btn-group {
      display: flex;
      gap: 1rem;
      flex-wrap: wrap;
    }
    
    .btn {
      padding: 0.75rem 1.5rem;
      border: none;
      border-radius: 8px;
      font-size: 0.95rem;
      font-weight: 600;
      cursor: pointer;
      transition: all 0.2s;
    }
    
    .btn-primary {
      background: #3b82f6;
      color: white;
    }
    
    .btn-primary:hover {
      background: #2563eb;
      transform: translateY(-2px);
      box-shadow: 0 4px 12px rgba(59, 130, 246, 0.4);
    }
    
    .btn-secondary {
      background: #6b7280;
      color: white;
    }
    
    .btn-secondary:hover {
      background: #4b5563;
    }
    
    .btn-outline {
      background: transparent;
      border: 2px solid #3b82f6;
      color: #3b82f6;
    }
    
    .btn-outline:hover {
      background: #3b82f6;
      color: white;
    }
  </style>
</head>
<body>
  <div class="btn-group">
    <button class="btn btn-primary">Primary Button</button>
    <button class="btn btn-secondary">Secondary Button</button>
    <button class="btn btn-outline">Outline Button</button>
  </div>
</body>
</html>`,
  },

  tailwind: {
    default: `<!-- Modern Card Component with Tailwind CSS -->
<div class="min-h-screen bg-gray-50 flex items-center justify-center p-6">
  <div class="max-w-md w-full">
    <div class="bg-white rounded-2xl shadow-xl overflow-hidden">
      <!-- Card Header with Gradient -->
      <div class="bg-gradient-to-br from-purple-600 via-purple-500 to-pink-500 px-6 py-8">
        <h2 class="text-2xl font-bold text-white mb-2">
          PixelPro Component
        </h2>
        <p class="text-purple-100">
          AI-powered generation at your fingertips
        </p>
      </div>

      <!-- Card Body -->
      <div class="p-6">
        <p class="text-gray-600 leading-relaxed mb-6">
          This component showcases the power of Tailwind CSS with beautiful 
          gradients, smooth transitions, and responsive design patterns.
        </p>

        <!-- Feature List -->
        <ul class="space-y-3 mb-6">
          <li class="flex items-center gap-3">
            <div class="w-5 h-5 rounded-full bg-green-100 flex items-center justify-center">
              <svg class="w-3 h-3 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
              </svg>
            </div>
            <span class="text-gray-700">Fully responsive</span>
          </li>
          <li class="flex items-center gap-3">
            <div class="w-5 h-5 rounded-full bg-green-100 flex items-center justify-center">
              <svg class="w-3 h-3 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
              </svg>
            </div>
            <span class="text-gray-700">Easy to customize</span>
          </li>
          <li class="flex items-center gap-3">
            <div class="w-5 h-5 rounded-full bg-green-100 flex items-center justify-center">
              <svg class="w-3 h-3 text-green-600" fill="currentColor" viewBox="0 0 20 20">
                <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"/>
              </svg>
            </div>
            <span class="text-gray-700">Production ready</span>
          </li>
        </ul>

        <!-- Action Button -->
        <button class="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-semibold py-3 px-6 rounded-xl transition-all duration-200 transform hover:scale-[1.02] active:scale-[0.98]">
          Get Started
        </button>
      </div>
    </div>
  </div>
</div>`,

    form: `<!-- Modern Login Form with Tailwind CSS -->
<div class="min-h-screen bg-gradient-to-br from-gray-900 via-purple-900 to-violet-900 flex items-center justify-center p-4">
  <div class="w-full max-w-md">
    <!-- Card -->
    <div class="bg-white/10 backdrop-blur-lg rounded-3xl shadow-2xl p-8 border border-white/20">
      <!-- Header -->
      <div class="text-center mb-8">
        <h2 class="text-3xl font-bold text-white mb-2">Welcome Back</h2>
        <p class="text-gray-300">Sign in to continue to PixelPro</p>
      </div>

      <!-- Form -->
      <form class="space-y-5">
        <!-- Email Input -->
        <div>
          <label class="block text-sm font-medium text-gray-200 mb-2">Email</label>
          <input 
            type="email" 
            placeholder="you@example.com"
            class="w-full px-4 py-3 rounded-xl bg-white/10 border border-white/20 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition"
          />
        </div>

        <!-- Password Input -->
        <div>
          <label class="block text-sm font-medium text-gray-200 mb-2">Password</label>
          <input 
            type="password" 
            placeholder="••••••••"
            class="w-full px-4 py-3 rounded-xl bg-white/10 border border-white/20 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent transition"
          />
        </div>

        <!-- Remember & Forgot -->
        <div class="flex items-center justify-between text-sm">
          <label class="flex items-center gap-2 text-gray-300">
            <input type="checkbox" class="w-4 h-4 rounded border-gray-300" />
            Remember me
          </label>
          <a href="#" class="text-purple-400 hover:text-purple-300">Forgot password?</a>
        </div>

        <!-- Submit Button -->
        <button 
          type="submit"
          class="w-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-semibold py-3 px-6 rounded-xl transition-all duration-200 transform hover:scale-[1.02] active:scale-[0.98]"
        >
          Sign In
        </button>
      </form>

      <!-- Divider -->
      <div class="flex items-center gap-4 my-6">
        <div class="flex-1 h-px bg-white/20"></div>
        <span class="text-gray-400 text-sm">or</span>
        <div class="flex-1 h-px bg-white/20"></div>
      </div>

      <!-- Social Login -->
      <div class="grid grid-cols-2 gap-3">
        <button class="flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white transition">
          <svg class="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
            <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
            <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
            <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
            <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
          </svg>
          Google
        </button>
        <button class="flex items-center justify-center gap-2 py-3 px-4 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white transition">
          <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
          </svg>
          GitHub
        </button>
      </div>

      <!-- Sign Up Link -->
      <p class="text-center mt-6 text-gray-300">
        Don't have an account? 
        <a href="#" class="text-purple-400 hover:text-purple-300 font-medium">Sign up</a>
      </p>
    </div>
  </div>
</div>`,
  },

  react: {
    default: `import React, { useState } from 'react';

/**
 * Modern Card Component
 * Generated by PixelPro AI
 * 
 * A reusable card component with hover effects and animations.
 * Built with React and Tailwind CSS.
 */

interface CardProps {
  title?: string;
  description?: string;
  features?: string[];
  onAction?: () => void;
}

const Card: React.FC<CardProps> = ({
  title = "PixelPro Component",
  description = "AI-powered generation at your fingertips",
  features = [
    "Fully responsive",
    "TypeScript support",
    "Easy to customize",
    "Production ready"
  ],
  onAction
}) => {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-6">
      <div 
        className="max-w-md w-full"
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
      >
        <div className={\`
          bg-white rounded-2xl shadow-xl overflow-hidden
          transition-all duration-300
          \${isHovered ? 'shadow-2xl -translate-y-2' : ''}
        \`}>
          {/* Gradient Header */}
          <div className="bg-gradient-to-br from-purple-600 via-purple-500 to-pink-500 px-6 py-8">
            <h2 className="text-2xl font-bold text-white mb-2">
              {title}
            </h2>
            <p className="text-purple-100">
              {description}
            </p>
          </div>

          {/* Content */}
          <div className="p-6">
            <p className="text-gray-600 leading-relaxed mb-6">
              This component showcases the power of React with Tailwind CSS,
              featuring smooth animations and interactive elements.
            </p>

            {/* Feature List */}
            <ul className="space-y-3 mb-6">
              {features.map((feature, index) => (
                <FeatureItem key={index} text={feature} />
              ))}
            </ul>

            {/* Action Button */}
            <button
              onClick={onAction}
              className="w-full bg-gradient-to-r from-purple-600 to-pink-600 
                         hover:from-purple-700 hover:to-pink-700
                         text-white font-semibold py-3 px-6 rounded-xl 
                         transition-all duration-200 transform 
                         hover:scale-[1.02] active:scale-[0.98]
                         focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2"
            >
              Get Started
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

/**
 * Feature Item Component
 * Displays a single feature with a checkmark icon
 */
const FeatureItem: React.FC<{ text: string }> = ({ text }) => (
  <li className="flex items-center gap-3 group">
    <div className="w-5 h-5 rounded-full bg-green-100 group-hover:bg-green-200 flex items-center justify-center transition-colors">
      <svg 
        className="w-3 h-3 text-green-600" 
        fill="currentColor" 
        viewBox="0 0 20 20"
      >
        <path 
          fillRule="evenodd" 
          d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" 
          clipRule="evenodd"
        />
      </svg>
    </div>
    <span className="text-gray-700 group-hover:text-gray-900 transition-colors">
      {text}
    </span>
  </li>
);

export default Card;`,

    button: `import React, { ButtonHTMLAttributes, forwardRef } from 'react';

/**
 * Button Component
 * Generated by PixelPro AI
 * 
 * A flexible button component with multiple variants and sizes.
 * Built with React and Tailwind CSS.
 */

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger';
type ButtonSize = 'sm' | 'md' | 'lg';

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: ButtonVariant;
  size?: ButtonSize;
  isLoading?: boolean;
  leftIcon?: React.ReactNode;
  rightIcon?: React.ReactNode;
}

const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      children,
      variant = 'primary',
      size = 'md',
      isLoading = false,
      leftIcon,
      rightIcon,
      className = '',
      disabled,
      ...props
    },
    ref
  ) => {
    // Variant styles
    const variantStyles = {
      primary: 'bg-blue-600 hover:bg-blue-700 text-white shadow-lg shadow-blue-500/50',
      secondary: 'bg-gray-600 hover:bg-gray-700 text-white',
      outline: 'border-2 border-blue-600 text-blue-600 hover:bg-blue-50',
      ghost: 'text-gray-700 hover:bg-gray-100',
      danger: 'bg-red-600 hover:bg-red-700 text-white shadow-lg shadow-red-500/50',
    };

    // Size styles
    const sizeStyles = {
      sm: 'px-3 py-1.5 text-sm',
      md: 'px-4 py-2.5 text-base',
      lg: 'px-6 py-3 text-lg',
    };

    return (
      <button
        ref={ref}
        className={\`
          inline-flex items-center justify-center gap-2
          font-semibold rounded-lg
          transition-all duration-200
          transform active:scale-95
          focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500
          disabled:opacity-50 disabled:cursor-not-allowed disabled:transform-none
          \${variantStyles[variant]}
          \${sizeStyles[size]}
          \${className}
        \`}
        disabled={disabled || isLoading}
        {...props}
      >
        {isLoading ? (
          <Spinner size={size} />
        ) : (
          <>
            {leftIcon && <span className="inline-flex">{leftIcon}</span>}
            {children}
            {rightIcon && <span className="inline-flex">{rightIcon}</span>}
          </>
        )}
      </button>
    );
  }
);

Button.displayName = 'Button';

/**
 * Loading Spinner Component
 */
const Spinner: React.FC<{ size: ButtonSize }> = ({ size }) => {
  const sizeMap = {
    sm: 'w-4 h-4',
    md: 'w-5 h-5',
    lg: 'w-6 h-6',
  };

  return (
    <svg
      className={\`animate-spin \${sizeMap[size]}\`}
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
    >
      <circle
        className="opacity-25"
        cx="12"
        cy="12"
        r="10"
        stroke="currentColor"
        strokeWidth="4"
      />
      <path
        className="opacity-75"
        fill="currentColor"
        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
      />
    </svg>
  );
};

/**
 * Example Usage:
 * 
 * import Button from './Button';
 * 
 * function App() {
 *   return (
 *     <div className="flex gap-4 p-8">
 *       <Button variant="primary">Primary</Button>
 *       <Button variant="secondary">Secondary</Button>
 *       <Button variant="outline">Outline</Button>
 *       <Button variant="ghost">Ghost</Button>
 *       <Button variant="danger">Danger</Button>
 *       <Button isLoading>Loading...</Button>
 *     </div>
 *   );
 * }
 */

export default Button;`,
  },
};

// ============================================
// AI CODE GENERATION FUNCTION
// ============================================

/**
 * Initialize Google Generative AI
 * Falls back to mock responses if API key is not provided
 */
let genAI = null;
if (process.env.GEMINI_API_KEY) {
  genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  console.log("✅ Google Gemini AI initialized");
} else {
  console.warn("⚠️  No GEMINI_API_KEY found. Using mock responses. Get your key at: https://makersuite.google.com/app/apikey");
}

export async function generateMultiFrameworkCode(
  prompt,
  frameworks = ["react"]
) {
  const results = {};

  for (const framework of frameworks) {
    // Phase 2: still using mock responses
    if (mockResponses[framework]) {
      results[framework] = mockResponses[framework].default;
    } else {
      results[framework] = "// Unsupported framework";
    }
  }

  return results;
}

/**
 * Creates a detailed system prompt for the AI based on the framework
 */
function createSystemPrompt(prompt, framework) {
  const baseInstructions = `You are an expert frontend developer. Generate ONLY the code, no explanations or markdown formatting.`;
  
  const frameworkInstructions = {
    html: `
Generate a complete, standalone HTML file with embedded CSS.
Requirements:
- Use semantic HTML5
- Include <!DOCTYPE html> and complete HTML structure
- Embed CSS in <style> tags in the <head>
- Use modern CSS (flexbox, grid where appropriate)
- Make it responsive
- Use a clean, modern design
- Include proper meta tags
- Add comments explaining key sections

User request: ${prompt}
`,
    tailwind: `
Generate HTML with Tailwind CSS utility classes.
Requirements:
- Use Tailwind CSS utility classes only
- No custom CSS or <style> tags
- Make it fully responsive (use sm:, md:, lg: breakpoints)
- Use modern Tailwind patterns
- Include proper structure and semantic HTML
- Use Tailwind's color palette
- Add descriptive HTML comments

User request: ${prompt}
`,
    react: `
Generate a React functional component with TypeScript.
Requirements:
- Use TypeScript with proper interfaces/types
- Use React hooks (useState, useEffect if needed)
- Use Tailwind CSS for styling
- Export the component as default
- Include JSDoc comments for the component
- Make it reusable with props
- Include proper TypeScript types
- Use modern React patterns (functional components, hooks)
- Make it responsive

User request: ${prompt}
`
  };

  return baseInstructions + "\n\n" + frameworkInstructions[framework];
}

/**
 * Generates UI component code using Google Gemini AI
 * Falls back to mock responses if AI is unavailable
 * 
 * @param {string} prompt - User's component description
 * @param {string} framework - Target framework (html, tailwind, react)
 * @returns {Promise<string>} Generated code
 */
